<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" 
 	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	name="mybot_xacro">

	<!-- KINECT ATTACHMENT -->
	<xacro:include filename="$(find mybot_description)/urdf/sensors/kinect.xacro"/>
	<kinect_sensor parent="base_link">
		<origin xyz="0 0 0" rpy="0 0 0" />
	</kinect_sensor>
	
	<!-- LASER ATTACHMENT -->
	<xacro:include filename="$(find mybot_description)/urdf/sensors/hokuyo.xacro"/>
	<hokuyo_sensor parent="base_link">
		<origin xyz="0 0 0" rpy="0 0 0" />
	</hokuyo_sensor>

	<!-- Import all Gazebo-customization elements, including Gazebo colors, sensors, controller -->
  	<xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo" />
	
	<xacro:property name="length_wheel" value="0.05" />
	<xacro:property name="radius_wheel" value="0.0775" />
	<xacro:macro name="default_inertial" params="mass">
               <inertial>
                       <mass value="${mass}" />
                       <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                                iyy="1.0" iyz="0.0"
                                izz="1.0" />
               </inertial>
	</xacro:macro>
	
	<xacro:macro name="sphere_inertia" params="m r">
		<inertia
			ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
		    	iyy="${2*m*r*r/5}" iyz = "0"
		    	izz="${2*m*r*r/5}"
		/>
	</xacro:macro>

	<link name="base_footprint">
   		<visual>
			<geometry>
      				<box size="0.001 0.001 0.001"/>
     			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
   		</visual>
		<xacro:default_inertial mass="0.0001"/>
 	</link>

	<gazebo reference="base_footprint">
		<material>Gazebo/Green</material>
		<turnGravityOff>false</turnGravityOff>
	</gazebo>

	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 0" />
		<parent link="base_footprint" />
		<child link="base_link" />
	</joint>

	<link name="base_link">
		<visual>
			<!--origin xyz="0 0 0.0125" rpy="0 0 0"/-->
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<cylinder radius="0.225" length="0.025"/>
			</geometry>
			<material name="Cyan1">
				<color rgba="0 0.9 0.9 1.0"/>
			</material>
		</visual>
		<collision>
			<geometry>
       				<cylinder radius="0.225" length="0.025"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="10"/>
	</link>
	<!--front wheel -->	
	<link name="wheel_1">
	  
		  <visual>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <sphere radius="${radius_wheel/2}"/>
		    </geometry>
		    <material name="black">
			<color rgba="0 0 0 1"/>
		    </material>
		  </visual>
		
  		  <collision>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <sphere radius="${radius_wheel/2}"/>
		    </geometry>
		  </collision>

		  <inertial>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <mass value="1"/>
		    <sphere_inertia m="1" r="${radius_wheel/2}"/>
		  </inertial>
	</link>
	<!-- left wheel -->
 	<link name="wheel_2">
   		<visual>
     			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
     			</geometry>
			<!-- <origin rpy="0 1.5 0" xyz="-0.1 0.1 0"/> -->
			<origin rpy="0 0 0" xyz="0 0 0"/>
   			<material name="black"/>
   		</visual>
		<collision>
			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>

 	</link>
    	<!-- back wheel -->
	<link name="wheel_3">
	  
		  <visual>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <sphere radius="${radius_wheel/2}"/>
		    </geometry>
		    <material name="black">
			<color rgba="0 0 0 1"/>
		    </material>
		  </visual>
		
  		  <collision>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <sphere radius="${radius_wheel/2}"/>
		    </geometry>
		  </collision>

		  <inertial>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <mass value="1"/>
		    <sphere_inertia m="1" r="${radius_wheel/2}"/>
		  </inertial>
	</link>
	<!-- right wheel -->
 	<link name="wheel_4">
   		<visual>
     			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
     			</geometry>
		<!--	<origin rpy="0 1.5 0" xyz="-0.1 -0.1 0"/> -->
			<origin rpy="0 0 0" xyz="0 0 0" />
   			<material name="black"/>
   		</visual>
		<collision>
			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>

 	</link>

<!-- -->
 <joint name="base_to_wheel1" type="fixed">
   <parent link="base_link"/>
   <child link="wheel_1"/>
   <origin rpy="0 0 0" xyz="0.18 0 ${-radius_wheel/2}"/>
   <axis xyz="0 0 1" />
 </joint>

 <joint name="base_to_wheel2" type="continuous">
   <axis xyz="0 0 1" />
   <anchor xyz="0 0 0" />
   <limit effort="100" velocity="100" />
   <parent link="base_link"/>
   <child link="wheel_2"/>
   <origin rpy="-1.5707 0 0" xyz="0 -0.195 0"/>
</joint>
<!-- -->
 <joint name="base_to_wheel3" type="fixed">
   <parent link="base_link"/>
   <axis xyz="0 0 1" />
   <child link="wheel_3"/>
   <origin rpy="0 0 0" xyz="-0.18 0 ${-radius_wheel/2}"/>
 </joint>

 <joint name="base_to_wheel4" type="continuous">
   <parent link="base_link"/>
   <axis xyz="0 0 1" />
   <child link="wheel_4"/>
   <origin rpy="-1.5707 0 0" xyz="0 0.195 0"/>
 </joint>


</robot>
